import {
  Computer,
  Checkroom,
  Home,
  Spa,
  SportsBaseball,
  MenuBook,
  HealthAndSafety,
  ChildCare,
  Toys,
  DirectionsCar,
  Grass,
  Pets,
  MusicNote,
  BusinessCenter,
  Build,
} from '@mui/icons-material';

export const categories = [
  { id: 'electronics', name: 'Electronics', icon: <Computer /> },
  { id: 'fashion', name: 'Fashion', icon: <Checkroom /> },
  { id: 'home', name: 'Home & Kitchen', icon: <Home /> },
  { id: 'beauty', name: 'Beauty', icon: <Spa /> },
  { id: 'sports', name: 'Sports', icon: <SportsBaseball /> },
  { id: 'books', name: 'Books', icon: <MenuBook /> },
  { id: 'health', name: 'Health', icon: <HealthAndSafety /> },
  { id: 'baby', name: 'Baby', icon: <ChildCare /> },
  { id: 'toys', name: 'Toys', icon: <Toys /> },
  { id: 'automotive', name: 'Automotive', icon: <DirectionsCar /> },
  { id: 'garden', name: 'Garden', icon: <Grass /> },
  { id: 'pets', name: 'Pets', icon: <Pets /> },
  { id: 'music', name: 'Music', icon: <MusicNote /> },
  { id: 'office', name: 'Office', icon: <BusinessCenter /> },
  { id: 'tools', name: 'Tools', icon: <Build /> },
];
